export const QUERY_KEYS = Object.freeze({
  GET_LIST_USER: "GET_LIST_USER",
  LIST_NOTI: "LIST_NOTI",
  HOME_CONFIG: "HOME_CONFIG",
  CHECKOUT_CART: "CHECKOUT_CART",
  PROVINCE_DATA: "PROVINCE_DATA",
  CUSTOMER_ORDER_SHIPPING: "CUSTOMER_ORDER_SHIPPING",
});
